# Generated by Django 3.1.6 on 2021-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50, verbose_name='Dish name')),
                ('price', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('d_image', models.ImageField(upload_to='dishes')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
