# Generated by Django 3.1.6 on 2021-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='is_visible',
        ),
        migrations.AlterField(
            model_name='dish',
            name='d_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
