# Generated by Django 3.1.6 on 2021-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20210527_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default='default', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='d_image',
            field=models.ImageField(upload_to='', verbose_name='Dish image'),
        ),
    ]
