# Generated by Django 3.1.6 on 2021-06-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('com', models.TextField(verbose_name='Comment')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
