# Generated by Django 3.1.6 on 2021-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210603_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Personal',
            field=models.BooleanField(default=False),
        ),
    ]
