# Generated by Django 3.1.6 on 2021-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('main_app', '0004_user_is_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_order', models.BooleanField(default=False)),
                ('c_dishes', models.ManyToManyField(blank=True, related_name='Related_cart', to='products.Product')),
            ],
        ),
    ]
