# Generated by Django 3.1.6 on 2021-06-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20210527_0810'),
        ('main_app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addition',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c_dishes',
            field=models.ManyToManyField(blank=True, related_name='Related_cart', to='dishes.Dish'),
        ),
    ]
