# Generated by Django 3.1.6 on 2021-05-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
    ]
